# Generated by Django 5.2 on 2025-04-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('expert', models.CharField(blank=True, max_length=100, null=True)),
                ('ups_power', models.CharField(blank=True, max_length=20, null=True)),
                ('install_date', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_count', models.IntegerField(blank=True, null=True)),
                ('battery_model', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_amp', models.CharField(blank=True, max_length=20, null=True)),
                ('battery_voltage', models.CharField(blank=True, max_length=20, null=True)),
                ('ups_serial', models.CharField(blank=True, max_length=50, null=True)),
                ('charge_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
