# Generated by Django 5.2 on 2025-05-28 05:58

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UPSBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('expert', models.CharField(blank=True, max_length=100, null=True)),
                ('ups_power', models.CharField(blank=True, max_length=20, null=True)),
                ('install_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('last_battery_installed_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('battery_count', models.IntegerField(blank=True, null=True)),
                ('battery_amp', models.CharField(blank=True, max_length=20, null=True)),
                ('battery_voltage', models.CharField(blank=True, max_length=20, null=True)),
                ('ups_serial', models.CharField(blank=True, max_length=50, null=True)),
                ('charge_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('battery_status', models.CharField(blank=True, max_length=100)),
                ('battery_model', models.ManyToManyField(blank=True, to='branches.batterymodel', verbose_name='مدل باتری')),
                ('ups_brand', models.ManyToManyField(blank=True, to='branches.upsbrand', verbose_name='برند UPS')),
            ],
        ),
    ]
