# Generated by Django 5.2 on 2025-04-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='battery_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
