# Generated by Django 5.2 on 2025-04-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_battery_status_branch_grade_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_battery_installed_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
