# Generated by Django 5.2 on 2025-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_last_battery_installed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='ups_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
