# Generated by Django 5.2 on 2025-05-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_ups_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='battery_model',
        ),
        migrations.AddField(
            model_name='branch',
            name='battery_model',
            field=models.ManyToManyField(blank=True, to='branches.batterymodel', verbose_name='مدل باتری'),
        ),
    ]
