# Generated by Django 5.2 on 2025-05-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_batterymodel_remove_branch_battery_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPSBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='ups_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.upsbrand', verbose_name='برند UPS'),
        ),
    ]
