# Generated by Django 5.2 on 2025-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_upsbrand_alter_branch_ups_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='ups_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
