# Generated by Django 5.2 on 2025-05-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_alter_branch_ups_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UPSBrand',
        ),
    ]
