# Generated by Django 5.2 on 2025-05-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_delete_upsbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPSBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
