# Generated by Django 5.2 on 2025-05-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_upsbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='ups_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.upsbrand'),
        ),
    ]
