# Generated by Django 5.2 on 2025-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_alter_branch_ups_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='ups_brand',
        ),
        migrations.AddField(
            model_name='branch',
            name='ups_brand',
            field=models.ManyToManyField(blank=True, to='branches.upsbrand', verbose_name='برند UPS'),
        ),
    ]
