# Generated by Django 5.2 on 2025-05-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_remove_branch_ups_brand_branch_ups_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
