# Generated by Django 5.2 on 2025-05-20 07:24

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_alter_branch_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='install_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_battery_installed_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
