# Generated by Django 5.2 on 2025-05-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_alter_branch_install_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='install_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='last_battery_installed_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
